apiVersion: autoscaling/v2beta1
kind: HorizantalAutoPodScaler
metadata:
   name: javawebdeploymentautoscaler
spec:
   scaleTargetRef:
      apiVersion: apps/v1
      kind: Deployment
      name: javawebappdeployment
   minReplicas: 2
   maxReplicas: 5
   metrics:
      - resource:
           name: cpu
           targetAverageUtillization: 50
        type: Resource
