apiVersion: apps/v1
kind: ReplicaSet
metadata:
   name: mongodb
   namespace: prod
spec: 
   replicas: 1
   selector:
      matchLabels:
         run: mongo
   template:
      metadata:
         name: mongo-pod
         labels:
            run: mongo
      spec:
         containers:
         - name: mongodbcontainer
           image: mongo
           ports:
           - containerPort: 27017
           env:
           - name: MONGO_INITDB_ROOT_USERNAME
             valueFrom:
                configMapKeyRef:
                    name: mongo-username
                    key: username
           - name: MONGO_INITDB_ROOT_PASSWORD
             valueFrom:
                 secretKeyRef: 
                    name: mongodbpwd
                    key: password
