apiVersion: v1
kind: Pod
metadata:
   name: javawebapppod
   namespace: prod
   labels:
     app: javawebapp
spec:
   containers:
   - name: javawebappcontainer
     image: uday745/maven-web-application:1.1
     ports:
     - containerPort: 8080
