apiVersion: v1
kind: Service
metadata:
   name: javawebappsvc
   namespace: prod
spec:
   type: NodePort
   ports:
   - port: 80
     targetPort: 8080
     nodePort: 30375
   selector:
     app: javawebapp
