apiVersion: apps/v1
kind: Deployment
metadata: 
   name: java-web-app
   namespace: prod
spec:
   replicas: 2
   strategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 1
        maxSurge: 1
   minReadySeconds: 30
   selector:
      matchLabels:
         app: java-web-app
   template:
      metadata:
         name: java-web-app-pod
         labels:
            app: java-web-app
      spec:
         containers:
         - name: web-app-container
           image: uday745/javawebapp:4.0
           ports:
           - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
   name: java-svc
   namespace: prod
spec:
   type: LoadBalancer
   selector:
      app: java-web-app
   ports:
   - port: 80
     targetPort: 8080

           
