apiVersion: apps/v1
kind: Deployment
metadata:
   name: javawebapp
   namespace: prod
spec:
   strategy:
      type: RollingUpdate
      rollingUpdate:
         maxSurge: 1
         maxUnavailable: 1
   replicas: 2
   selector:
      matchLabels:
         app: java-web
   template:
      metadata:
         name: java-web-app-pod
         labels:
            app: java-web
      spec:
         affinity:
            nodeAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 1
                preference:
                   matchExpressions:
                   - key: name
                     operator: In
                     values:
                     - Wworker1
         containers:
         - name: java-web-app
           image: dockerhandson/java-web-app
           ports:
           - containerPort: 8080
           readinessProbe:
              httpGet:
                 path: /java-web-app
                 port: 8080
              initialDelaySeconds: 15
              timeoutSeconds: 5
              periodSeconds: 10
           livenessProbe: 
              httpGet:
                 path: /java-web-app
                 port: 8080
              initialDelaySeconds: 15
              timeoutSeconds: 5
              periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata: 
   name: java-web-app-svc
   namespace: prod
spec:
   type: NodePort
   selector:
      app: java-web
   ports:
   - port: 80
     targetPort: 8080
     nodePort: 30375
