kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
    name: readonly
    namespace: default
rules:
- apiGroups: ["*"]
  resources: ["pods","services"]
  verbs: ["get","list","create"]
- apiGroups: ["apps"]
  resources: ["deployments","daemonsets","replicasets"]
  verbs: ["get","list","create","update"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
   name: read-access-binding
   namespace: default
subjects:
- kind: User
  name: uday
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: readonly
  apiGroup: rbac.authorization.k8s.io
