apiVersion: v1
kind: Service
metadata:
   name: springapp
   namespace: prod
spec:
   type: NodePort
   selector:
      app: springapp
   ports:
   - port: 8081
     targetPort: 8080
     nodePort: 30375
