apiVersion: v1
kind: PersistentVolume
metadata:
   name: pv-nfs-vol1
   labels:
      type: local
spec:
   storageClassName: nfs-storageclass
   capacity:
      storage: 200Mi
   accessModes: 
      - ReadWriteOnce
   nfs:
      server: 172.31.12.244
      path: "/mnt/nfs_share/pv1"
