apiVersion: apps/v1
kind: StatefulSet
metadata:
   name: nginx-sts
spec:
   serviceName: "nginx-headless"
   replicas: 4
   selector:
      matchLabels:
         run: nginx-demo
   template:
      metadata:
         labels:
            run: nginx-demo
      spec:
          containers:
          - name: nginx
            image: nginx
            volumeMounts:
            - name: www
              mountPath: /var/www
   volumeClaimTemplates:
   - metadata:
        name: www
     spec:
       storageClassName: nfs-storageclass 
       accessModes:
         - ReadWriteOnce
       resources:
         requests:
           storage: 100Mi       
