apiVersion: v1
kind: Service
metadata:
   name: nginx-headless
   labels:
      run: nginx-demo
spec:
    ports:
    - port: 80
      name: web
    clusterIP: None
    selector:
       run: nginx-demo
