apiVersion: v1
kind: Service
metadata: 
  name: my-app-svc
  namespace: prod
  labels:
     app: my-app
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: http
  selector:
    app: my-app
    version: v1.0.0

