apiVersion: v1
kind: Service
metadata:
   name: spring-app
   namespace: prod
spec:
   type: NodePort
   ports:
   - port: 80
     targetPort: 8080
     nodePort: 30375
   selector:
      app: springapp
