apiVersion: v1
kind: PersistentVolume
metadata:
   name: pv-nfs-vol1
   labels:
      type: label
spec:
   storageClassName: mannual
   capacity:
      storage: 1Gi
   accessModes:
      - ReadWriteMany
   nfs:
      server: "172.31.12.244"
      path: "/mnt/share"
