apiVersion: v1
kind: PersistentVolume
metadata:
   name: pv-nfs-vol1
   labels:
      type: local
spec:
   storageClassName: manual
   capacity:
      storage: 1Gi
   accessModes:
      - ReadWriteMany
   nfs:
      server: 172.31.12.244
      path: "/mnt/nfs_share"
