apiVersion: v1
kind: PersistentVolumeClaim
metadata:
   name: pvc-nfs-vol1
   namespace: prod
spec:
   storageClassName: manual
   accessModes:
     - ReadWriteMany
   resources:
     requests:
        storage: 500Mi
