apiVersion: v1
kind: PersistentVolumeClaim
metadata:
   name: pvc-hostpath
   namespace: prod
spec:
   storageClassName: mannual
   accessModes:
     - ReadWriteOnce
   resources:
     requests:
        storage: 500Mi
